import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import * as snarkjs from 'snarkjs';
import fs from 'fs/promises';
import path from 'path';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { proof, publicSignals, nullifier, rating, subjectId } = body;

    if (
      !proof ||
      typeof proof !== 'object' ||
      !Array.isArray(publicSignals) ||
      typeof nullifier !== 'string'
    ) {
      return NextResponse.json({ error: 'Missing or invalid proof data' }, { status: 400 });
    }

    // Load verification key
    const vkeyPath = path.join(process.cwd(), 'public', 'wasm', 'vkey.json');
    let vkeyJson;
    try {
      vkeyJson = await fs.readFile(vkeyPath, 'utf8');
    } catch (err) {
      return NextResponse.json({ error: 'Verification key not found on server' }, { status: 500 });
    }
    const vkey = JSON.parse(vkeyJson);

    // Verify cryptographic proof
    const isValid = await snarkjs.groth16.verify(vkey, publicSignals, proof);
    if (!isValid) {
      return NextResponse.json({ error: 'Invalid ZK proof' }, { status: 400 });
    }

    // Enforce nullifier uniqueness server-side
    // The nullifier must match the one generated by the circuit to prevent replay attacks
    const expectedNullifier = BigInt(publicSignals[1]).toString(16).padStart(64, '0');
    if (nullifier !== expectedNullifier) {
      return NextResponse.json({ error: 'Nullifier does not match proof' }, { status: 400 });
    }

    const existingReview = await prisma.review.findUnique({
      where: { nullifier: expectedNullifier },
    });

    if (existingReview) {
      return NextResponse.json({ error: 'Nullifier already used' }, { status: 409 });
    }

    return NextResponse.json({ success: true, message: 'Proof verified and nullifier is unique' }, { status: 200 });
  } catch (error) {
    console.error('Verify proof error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
